### PR TITLE
Make the standard Voice configuarble

### PR DESCRIPTION
**Pull request by Handfeger**
I've made the Standard Text-to-Speech voice available in the configuration, where you can choose from all Installed Voices (like the drop-down in Voice Attack).

Since this is my first time working with C# I only got the code building in the debug environment. So make sure to review the changes for rookie mistakes.
I also haven't included Tests, because I couldn't find a file that actually tests the `configuration.exe`.

I have tested the debug version and it actually uses the configured voice.

Please let me know if changes like this are appreciated.

Greetings CMDR Creeprr

### CODE REVIEW

**Comment by Handfeger** [comment]
So is the close just a no to the feature request of being able to select a voice, or was my code so bad that you want to implement the feature yourself?

**Comment by cmdrmcdonald** [comment]
Sorry this auto-closed when the feature branch was deleted, and for some reason I hadn't received a notification when it was created.

I'll take a look at this and see what it's doing.  Would it be possible to create a PR against the develop branch?

I will say, however, that I want to make the voice configuration available on a per-ship basis to allow for different voices as well as different modulations for each voice so I'm not sure how this would mesh with that idea.

**Comment by Handfeger** [comment]
Well it was a fast fix because I am playing on a German system and the english with german tts isn't understandable. I will look into a new pull request later this evening. Maybe also look into your thoughts while I'm at it.

**Comment by cmdrmcdonald** [comment]
My thought was to have a default voice in the 'EDDI' section and then the ability to also select one for each ship in the 'Shipyard' section (with a 'default' option if they don't want to do so).

There are also a number of parameters for each voice beyond just the name though (chorus/reverb/distortion/etc) so there would need to be some thought in to where all these fitted, and how to explain them to the user.  It might be that the easiest solution is to have a pop-up window where the user selected the voice and parameters, and had a 'test' button that would say something to allow the user to get a feel of how the voice sounds.  This could then be reused for both the default voice as well as the per-ship voice.

**Pull request closed without merging**
